// Generated by CoffeeScript 1.3.3
(function() {
  var js;

  js = document.createElement('script');

  js.setAttribute('data-base', chrome.extension.getURL('/'));

  js.src = chrome.extension.getURL("js/turntablecli.js?v=1_" + (new Date().getTime()));

  js.id = 'turntablecli';

  document.body.appendChild(js);

}).call(this);
